version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/site.conf
            - ./webroot:/var/www/html
        links:
            - php7
            - php5
    php7:
        image: php:7-fpm-alpine
        volumes:
            - ./webroot:/var/www/html
    php5:
        image: php:5-fpm-alpine
        volumes:
            - ./webroot:/var/www/html
